spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        default_batch_fetch_size: 100

  redis:
    host: localhost
    port: 6379